import Head from "next/head";
import { Button } from "../stories/Button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-300 h-screen">
        <Button label="Storybook button with tailwind" tailwind />
      </main>
    </>
  );
}
